name:                modusponens-prototype
version:             0.1.0.0
github:              "githubuser/modusponens-prototype"
license:             BSD3
author:              "Marton Bognar and Georgios Karachalias"
maintainer:          "marton.bognar@student.kuleuven.be"
copyright:           "2019 - 2020 Marton Bognar and Georgios Karachalias"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/modusponens-prototype#readme>

dependencies:
- base >= 4.7 && < 5
- pretty
- mtl
- parsec

library:
  source-dirs: src

executables:
  modusponens-prototype-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - modusponens-prototype

